"""Infrastructure for QA Agent Visualization Cache API.

This component creates an API Lambda that serves cached QA visualization data.
The cache is generated by the QA Agent Step Function's EMR Spark job
(qa_viz_cache_job.py) and stored in S3.

API:
    GET /qa/visualization             → metadata.json (question count, stats)
    GET /qa/visualization?index=3     → single question trace JSON
    GET /qa/visualization?all=true    → all questions (for SSG/build-time)
"""

import json
import os
from typing import Optional

import pulumi
import pulumi_aws as aws
from pulumi import (
    AssetArchive,
    ComponentResource,
    FileArchive,
    Input,
    Output,
    ResourceOptions,
)

stack = pulumi.get_stack()

LAMBDAS_DIR = os.path.join(os.path.dirname(__file__), "lambdas")


class QAVizCache(ComponentResource):
    """API Lambda for serving QA Agent visualization cache data.

    The cache is generated by the QA Agent Step Function pipeline
    and stored in S3. This component provides an API to serve it.
    """

    def __init__(
        self,
        name: str,
        *,
        cache_bucket_name: Input[str],
        opts: Optional[ResourceOptions] = None,
    ):
        super().__init__(
            f"custom:qa-viz-cache:{name}",
            name,
            None,
            opts,
        )

        region = aws.get_region().name
        account_id = aws.get_caller_identity().account_id
        cache_bucket_output = Output.from_input(cache_bucket_name)

        self.cache_bucket_name = cache_bucket_output

        # ============================================================
        # API Lambda Role
        # ============================================================
        self.api_lambda_role = aws.iam.Role(
            f"{name}-api-role",
            assume_role_policy=json.dumps(
                {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Principal": {"Service": "lambda.amazonaws.com"},
                            "Action": "sts:AssumeRole",
                        }
                    ],
                }
            ),
            tags={"environment": stack},
            opts=ResourceOptions(parent=self),
        )

        # API Lambda policy - read from cache bucket
        aws.iam.RolePolicy(
            f"{name}-api-policy",
            role=self.api_lambda_role.id,
            policy=cache_bucket_output.apply(
                lambda bucket: json.dumps(
                    {
                        "Version": "2012-10-17",
                        "Statement": [
                            {
                                "Effect": "Allow",
                                "Action": [
                                    "logs:CreateLogGroup",
                                    "logs:CreateLogStream",
                                    "logs:PutLogEvents",
                                ],
                                "Resource": f"arn:aws:logs:{region}:{account_id}:*",
                            },
                            {
                                "Effect": "Allow",
                                "Action": ["s3:GetObject", "s3:ListBucket"],
                                "Resource": [
                                    f"arn:aws:s3:::{bucket}",
                                    f"arn:aws:s3:::{bucket}/*",
                                ],
                            },
                        ],
                    }
                )
            ),
            opts=ResourceOptions(parent=self),
        )

        # ============================================================
        # API Lambda (GET endpoint)
        # ============================================================
        self.api_lambda = aws.lambda_.Function(
            f"{name}-api-lambda",
            runtime="python3.12",
            architectures=["arm64"],
            role=self.api_lambda_role.arn,
            code=AssetArchive({".": FileArchive(LAMBDAS_DIR)}),
            handler="index.handler",
            environment=aws.lambda_.FunctionEnvironmentArgs(
                variables={
                    "S3_CACHE_BUCKET": cache_bucket_output,
                }
            ),
            memory_size=256,
            timeout=30,
            tags={"environment": stack},
            opts=ResourceOptions(parent=self),
        )

        aws.cloudwatch.LogGroup(
            f"{name}-api-lambda-logs",
            name=self.api_lambda.name.apply(lambda n: f"/aws/lambda/{n}"),
            retention_in_days=30,
            opts=ResourceOptions(parent=self),
        )

        # ============================================================
        # Exports
        # ============================================================
        self.register_outputs(
            {
                "api_lambda_arn": self.api_lambda.arn,
                "api_lambda_name": self.api_lambda.name,
                "cache_bucket_name": self.cache_bucket_name,
            }
        )


def create_qa_viz_cache(
    cache_bucket_name: Input[str],
    opts: Optional[ResourceOptions] = None,
) -> QAVizCache:
    """Factory function to create QA Viz Cache API.

    Args:
        cache_bucket_name: Name of the S3 bucket containing viz-cache data.
        opts: Pulumi resource options.
    """
    return QAVizCache(
        f"qa-viz-cache-{stack}",
        cache_bucket_name=cache_bucket_name,
        opts=opts,
    )
