import Foundation
import VisionPortraitCore

private struct Arguments {
    let input: URL
    let manifest: URL
    let mask: URL
    let check: Bool
    let validateOnly: Bool

    init(_ values: [String]) throws {
        var inputPath: String?
        var manifestPath: String?
        var maskPath: String?
        var check = false
        var validateOnly = false
        var index = 1
        while index < values.count {
            switch values[index] {
            case "--input":
                index += 1
                guard index < values.count else {
                    throw VisionPortraitError.invalidArguments("--input requires a path")
                }
                inputPath = values[index]
            case "--manifest":
                index += 1
                guard index < values.count else {
                    throw VisionPortraitError.invalidArguments("--manifest requires a path")
                }
                manifestPath = values[index]
            case "--mask":
                index += 1
                guard index < values.count else {
                    throw VisionPortraitError.invalidArguments("--mask requires a path")
                }
                maskPath = values[index]
            case "--check":
                check = true
            case "--validate-only":
                validateOnly = true
            case "--help", "-h":
                Self.printUsage()
                Foundation.exit(EXIT_SUCCESS)
            default:
                throw VisionPortraitError.invalidArguments("Unknown argument: \(values[index])")
            }
            index += 1
        }
        guard let inputPath, let manifestPath, let maskPath else {
            throw VisionPortraitError.invalidArguments(
                "--input, --manifest, and --mask are required"
            )
        }
        guard !check || !validateOnly else {
            throw VisionPortraitError.invalidArguments(
                "--check and --validate-only are mutually exclusive"
            )
        }
        input = URL(fileURLWithPath: inputPath).standardizedFileURL
        manifest = URL(fileURLWithPath: manifestPath).standardizedFileURL
        mask = URL(fileURLWithPath: maskPath).standardizedFileURL
        self.check = check
        self.validateOnly = validateOnly
    }

    static func printUsage() {
        print(
            """
            usage: vision-portrait-worker \\
              --input <portrait.jpg> \\
              --manifest <vision-portrait-v1.json> \\
              --mask <vision-person-mask-v1.json> [--check | --validate-only]

            Runs Apple Vision locally. --check compares generated bytes with the
            checked-in artifacts without writing them. --validate-only checks
            the committed artifact contract without invoking Vision inference.
            """
        )
    }
}

private func relativePublicPath(for artifact: URL) -> String {
    let components = artifact.pathComponents
    if let publicIndex = components.lastIndex(of: "public") {
        return "/" + components.dropFirst(publicIndex + 1).joined(separator: "/")
    }
    return "/rotoscope/" + artifact.lastPathComponent
}

private func writeOrCheck(_ data: Data, at url: URL, check: Bool) throws {
    if check {
        guard FileManager.default.fileExists(atPath: url.path) else {
            throw VisionPortraitError.artifactMismatch("Missing artifact: \(url.path)")
        }
        let existing = try Data(contentsOf: url)
        guard existing == data else {
            throw VisionPortraitError.artifactMismatch("Stale artifact: \(url.path)")
        }
        return
    }
    try FileManager.default.createDirectory(
        at: url.deletingLastPathComponent(),
        withIntermediateDirectories: true
    )
    try data.write(to: url, options: .atomic)
}

do {
    let arguments = try Arguments(CommandLine.arguments)
    guard FileManager.default.fileExists(atPath: arguments.input.path) else {
        throw VisionPortraitError.invalidImage("Input image does not exist")
    }
    if arguments.validateOnly {
        let manifestData = try Data(contentsOf: arguments.manifest)
        let maskData = try Data(contentsOf: arguments.mask)
        let decoder = JSONDecoder()
        let manifest = try decoder.decode(VisionPortraitManifest.self, from: manifestData)
        let mask = try decoder.decode(PersonMaskArtifact.self, from: maskData)
        let analysis = VisionPortraitAnalysis(manifest: manifest, personMask: mask)
        try VisionPortraitValidator.validate(analysis)
        guard manifest.source.sha256 == StableJSON.sha256(try Data(contentsOf: arguments.input)),
              manifest.personMask?.sha256 == StableJSON.sha256(maskData),
              manifest.personMask?.path == relativePublicPath(for: arguments.mask)
        else {
            throw VisionPortraitError.artifactMismatch(
                "Vision artifacts do not match the portrait or mask"
            )
        }
        print(
            "validated \(manifest.features.count) Vision features, " +
                "\(manifest.primaryFace?.landmarkRegions.count ?? 0) face regions"
        )
    } else {
        let analysis = try VisionPortraitAnalyzer().analyze(
            imageURL: arguments.input,
            maskPublicPath: relativePublicPath(for: arguments.mask)
        )
        try VisionPortraitValidator.validate(analysis)
        guard let mask = analysis.personMask else {
            throw VisionPortraitError.invalidImage("Vision did not produce a primary-person mask")
        }
        let manifestData = try StableJSON.encode(analysis.manifest)
        let maskData = try StableJSON.encode(mask)
        try writeOrCheck(maskData, at: arguments.mask, check: arguments.check)
        try writeOrCheck(manifestData, at: arguments.manifest, check: arguments.check)
        let action = arguments.check ? "verified" : "generated"
        print(
            "\(action) \(analysis.manifest.features.count) Vision features, " +
                "\(analysis.manifest.primaryFace?.landmarkRegions.count ?? 0) face regions, " +
                "manifest \(StableJSON.sha256(manifestData)), mask \(StableJSON.sha256(maskData))"
        )
    }
} catch {
    fputs("vision-portrait-worker: \(error.localizedDescription)\n", stderr)
    Arguments.printUsage()
    Foundation.exit(EXIT_FAILURE)
}
