# Pre-commit hooks for code quality
# Install with: pip install pre-commit && pre-commit install

repos:
  # Python formatting
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.12
        files: '\.(py|pyi)$'

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: '\.(py|pyi)$'

  # Python type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies: [
          types-requests,
          types-boto3,
          types-python-dateutil,
          boto3-stubs[dynamodb,s3,lambda,stepfunctions]
        ]
        files: '\.(py|pyi)$'
        args: ["--ignore-missing-imports", "--no-strict-optional"]

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: '^\.github/workflows/.*\.yml$'
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["-ll", "-x", "tests/"]
        files: '\.(py|pyi)$'

# Configuration
default_language_version:
  python: python3.12

# Files to exclude
exclude: |
  (?x)^(
    .*\.egg-info/|
    \.git/|
    \.mypy_cache/|
    \.pytest_cache/|
    __pycache__/|
    build/|
    dist/|
    node_modules/|
    portfolio/|
    \.next/|
    venv/|
    \.venv/
  )