config:
  aws:region: us-east-1
  portfolio:OPENAI_API_KEY:
    secure: AAABANhLu9Xk4cxD7v1K8q1IRD5Lwtnr3cQTcuUOPWIBM80amq3juqBmrNtIUlWWoQAfIi3U8Pwht4vkU7kTzOryw13iDQUdHiB2D2LJl2Y8ZXMN97lftEASOScKZihcaiNWXSm9YAgDhLbR0HtRewr1XfRt6FlohCAzFu/KuphaJd4zy+PU0t1thvj8OAErHIxU4fUQL8rkwDcqqm+bnR1J4ag2UGz075zRbEfPJAWUnen0zsN34xUDlM/JXVRMBR4dhw==
  portfolio:environment: dev
  portfolio:GOOGLE_PLACES_API_KEY:
    secure: AAABAAK8xGIKbSJImf3isrPRyJRt+P7pDXSUshC3r34OoDik3KWknQmYuu0q+/KfLXLReYCPe4IXmWFDEpFNnE4kEnOl7SM=
  ml-training:force-rebuild: "true"
  lambda-layer:force-rebuild: "false"
  portfolio:PINECONE_API_KEY:
    secure: AAABAB6y1jBmasYCd0JbmQetWvndVC15ZSa7jtgyj2pNQ1y18JrMbJuCkSthuTX02pG7G2YYMmh4ee8Ck16UuQML90lKCiw3IIHBHK2dXNJeSI5ewuBW2KSdjLzhQA+K6bKNQCdYUT5O6N8=
  portfolio:PINECONE_INDEX_NAME: "receipt-validation-dev"
  portfolio:PINECONE_HOST: "https://receipt-validation-dev-sy23fax.svc.aped-4627-b74a.pinecone.io"
  portfolio:privateSubnetCidrs:
    - 10.10.10.0/24
    - 10.10.11.0/24
    - 10.10.12.0/24
    - 10.10.13.0/24
  portfolio:publicSubnetCidrs:
    - 10.10.0.0/24
    - 10.10.1.0/24
    - 10.10.2.0/24
    - 10.10.3.0/24
  portfolio:vpcCidr: 10.10.0.0/16
  lambda-layer:sync-mode: "true"
  portfolio:notification_emails:
    - "tnorlund@icloud.com" # Replace with your actual email address
