config:
  aws:region: us-east-1
  portfolio:OPENAI_API_KEY:
    secure: AAABALe0NIAr8rMxpYRRdx6BWX8J+bzJr49JLe1J2++tT73yTWw07XWdJP9Bvkp8Qki45BypvZGByqBcvkxjx4l83C/mJ+NYXwwoSnQ3vhzop+NuWKQ+SXnvtz/4cNj7EsnNo2uy16ZZ536x/dBH/sNSf64rbUnU/2zlAHtaVQKds4t3VAffvy8Cmo/4dMfW/PYpUG1ZpyXPwLv9XTPA/AL1F+dA6/V8uSOFwmI7Hu+ox654+HuKy4QdK8TqLczJQ97WPw==
  lambda-layer:force-rebuild: "false"
  portfolio:environment: prod
  portfolio:cloudFrontLogRetentionDays: "90"
  portfolio:googleAnalyticsMeasurementId: G-7TT64C825N
  portfolio:googleTagManagerId: GTM-PBZWT6NS
  ml-training:force-rebuild: "true"
  portfolio:PINECONE_INDEX_NAME: "receipt-validation-dev"
  portfolio:PINECONE_HOST: "https://receipt-validation-dev-sy23fax.svc.aped-4627-b74a.pinecone.io"
  portfolio:GOOGLE_PLACES_API_KEY:
    secure: AAABAJa1JM+ynYtukEgxlYR/hIjEC0SMpJ/JZeo064/xEgCk6o3/Vou7sbzH22r1zq9gMsdh5QdOKMHdW3JSww9DAfHIJdE=
  portfolio:privateSubnetCidrs:
    - 10.20.10.0/24
    - 10.20.11.0/24
    - 10.20.12.0/24
    - 10.20.13.0/24
  portfolio:publicSubnetCidrs:
    - 10.20.0.0/24
    - 10.20.1.0/24
    - 10.20.2.0/24
    - 10.20.3.0/24
  portfolio:vpcCidr: 10.20.0.0/16
  portfolio:PINECONE_API_KEY:
    secure: AAABANdW1oCKVnvnDvAqcO2g53fAPtzYXWNfnFQF9xIe8WDFZ3QKHfjcCoC6c5fLFRikzt9yQepRE4/lb+dBi/S62g5jRWozGWsYUuBGc2Kh6eYcWUQBZ8QHsopksZW3iEqZxvfxlcVOyp8=
  lambda-layer:sync-mode: "false"
  portfolio:notification_emails:
    - "tnorlund@icloud.com" # Replace with your actual email address for production alerts
  portfolio:use-static-base-image: "false" # Use content-based tags for production
  portfolio:docker-buildkit: "true" # Enable Docker BuildKit for caching
  portfolio:LANGCHAIN_API_KEY:
    secure: AAABAE4K3AaVrtBdO8r3+ooYvm3vIBvWIkXebe3gIY3SqhFlUfHP+6GOIp8+Bb8YG82KuGLhpNS9s8GTIldJQ4azObv9qXN1p1INBhHL3cBbmBw=
  portfolio:ecr-max-images: "4"
  portfolio:ecr-max-age-days: "7"
  docker-build:sync-mode: "true" # Wait for builds in prod
  docker-build:force-rebuild: "false"
  docker-build:debug-mode: "false"
  ml-training:enable-sagemaker: "true"
  portfolio:OPENROUTER_API_KEY:
    secure: AAABAO7+SJCT6LDKboMx7/VKP85FJcr+oO6qhoUVkLsMXsuV+9KlnSV1EP6xXDS+2+kU6qSiTOIQVkkS/Mej8F0Joqg615isPExbCJeEkauGxHgpNxSueMVwEAk4dMXkjX+mCC+9I2Sv
  portfolio:LANGSMITH_SERVICE_API_KEY:
    secure: AAABAE/vEZFs0Yo9hsM30Di3PAZUENpGkevmRx+he24laSy8gX2ThyzNOCrC4/RVy+xJxaGzLXIqj5O9DnmnAv7uTL5NC72RHPEh78iiuhClZrg=
  portfolio:LANGSMITH_TENANT_ID: 2586637a-4a13-4ad7-8bc1-2f8221e32c1b
  portfolio:CHROMA_CLOUD_API_KEY:
    secure: AAABALA2lRVioyilkPaleV5yFlRxPQU5cax7deey+jD4hu+Oh4K8TX3JOWogU6qfNnak8QVtlBx9KInVhilKvgUz7I0ookpeIYtHk/nKtQ==
  portfolio:CHROMA_CLOUD_TENANT: cf5b7019-a74c-4416-96cc-9578906bfc52
  portfolio:CHROMA_CLOUD_DATABASE: receipt_prod
  portfolio:CHROMA_CLOUD_ENABLED: "true"
  portfolio:gaPropertyId: "542366301"
  portfolio:gaServiceAccountKey:
    secure: AAABAOPsRSK3RrSnq/FZiIOsRkRYKoYZrk5WcaPI94ukAFxymTk4jzVTfxrYKDEN5A+OoPpVMjywYZVVuPLCgIWy4JgKcPAPqUHzSLLiHwGHMH4Z/XoLPBj5EMl0gbCkWntq8LaFXQ5N+Gh69ovaaieA2ZhwDt7JpkrbzenPF5WrqZQy3XWKVyq7b6UUh9XqMurcx8Ip7CGW+DEJ/B0Jo9nzkcC/dOe0ts00Oka1tp9sepo5Xx4Dv75RTwlfbaWf+3cRvPde+M7NgpQR3samgIa6RPeI24RbXDcNaJfMtfFp6THZlahmjr0kqMKp7HIOClW/uNiIt0rVFo4BFrlTYioGWWRb++rFCyjjQMzUCytzeUsXK1mFSxpT0J4Mk/vdA8p72mTD42etEtTcWniL8T0a9F6kkh9XWOSXYDLw2/0KjN+T+ff1C8DdlcwFSy2I/zJUGwoghe9Tu2sOz9qcsW8htJnttF7sVx+CrdSiN0nk79NYCW9p8ft39uQ7RwKYKI1iRTj7OBNIlZOyU3KA/uhbAPPe+oodceKP5360RYPKf6SrPBRRf5tre4r8+BQ1e7IKrk95aiFFuY1rHxmRweL9YWtkv2uqyjnr/ZOxDSe1uft3UsBti7u9Xd1m0xypTg6/NbigICL4KymRLkCuydjBKmlycV0ofAOwHx8CEomTTOMlCGAYpU6QfvNl0eKvJzufUFvDXcOMAZRDaOFzQhUvoj5Kr92BkSFa9spFE0OQabDs16yC+kaX19tEyCiVDcyYSwzzizrJS0pUczAi+sJgxOAUFtMK+KBbreFxwGbLzvaIe1YRZO4Ddz31EHuvgtV1nH8yoOMFXpURYd/XzXostrQdw50t4Gp61IShGEFI/ThTgaZ7/D3fMuwY7wVxgD3T/Nj4nsme7Jhgg4somfd+xaqivPQc66QctmFkO0p6BjHtf3Gw4y5kN+3oOWOUGcesNtj7M2gZiIEKjKR93ARNMXAwAkSN4aUtAwAnTzi6EFknqN8CHT2oFd1Yk0TTrHesUfDXZqJ6RKBjfwGMw0hALcVVjtoNXUWdTLhgW9dyVzvEICp4Yjesw/6ACJ/GgHS532FvDgbY9GiDz3V70TRYiB004yF1anP6JDG1L2RnZakEHy2fpy6U+YSiVdoUM5Y6J5p7eCkbbDN3PpB/xjsJEc5XrWxqK4fExq9o+vt1536NBc7RItcLr8jye1YgRii1jRgnN3nfAMuFREQhtzm4zkLw5COO4r/2D93SsNUgcfxUIN9iio96FIUFmseBsGDTuo/g603BHg1T9xhE7JeJqN9FDh5ViHhcRtq7iKvsllVISKXFlZmyMs5Ww9m8IUNE+EAVofzGwd2AEqUp4V2SsHdOTeUcTN7+nfhFBg7r1nxwbSZn8nQ/606Y24XuNyiOEUY6kCvTPx8JJBOUwifs9UrayyZSMRiDOdnsDE4xHmfsxE10kdWIICl6DhEXfRpO/Vv8umZNwgFhVSMnHgNS9FG7S3HJFU2+dX8q++0S9qwKIil8j/SS7uk+J8FWO7WlIZv7CZ8+LMUac7XYA/KCKTfAfIO6a/usXhtCas4UT1n1LO5fusrCjn+Z94Jkj8NWwJ6YkdN0zTTZ37pr9Fpz72sDBrQWrV5CJiBoq8zNm3kLMe7K1rkMgxcyNptANXHAw7OSbs35grXuR6ubP4q9P9/S0bvDeTlk1d1gXC8utirS2r95xmVQxGUjOIWreTun3rlGUe1V6QKaLchcV12nwnSdsGAQFcPyLmWDF0Zv9B+hdE3nvTEQyhHHfpHFBWbTYK6+bQlzH0MJ4eilXuTVBzokc1aFw2ob3/v7qrt2a8qSlV7xsJ2DAKn8ynzMPQV53AUv2N1TD2dd2kbt2WiD0tq1BUEB90A200dsZeQoAMv6ar14OvnoQA9XoR8EfaxeC9zdaRQAVphi8akc90WvRJyVLJNev2GV2QRSCy92Qp/ed7g/MR4bCNwQuHsbdAzctkO1xmfCBgjDfoZQwi/WWuAb5B8GaEk2n2h3WhOHjZNyfAh2DyHm4RW/9+4CS+4okxwQarrrzFh0Oepa8EqiPI0M8PytbbJQn/ZUWg0GSUFoq4GJ52RWSfd6nPrvPXCL0CHrMsDJU2oN3uTB2c2T7mcwmHUGtazHMy/EoYE/fywMCbMjq6pnM3YX91Ejl6cTjaB+0dpVRIOKX2Uz3JRuAnelnQVuF4qT5jwBL6tIZ8uFVfu1ady2uQXjGZRvanfJfcDkqmT/Ctf/jp+anPq1SBVE+hrEYu7WNTQbx64gTJoocycwbrTM1+QgGVEdxj2mk4kok5mqUqaFas7l6mi/dTdcCG22PJkKnhA0vfNT6Zoai2bhWn+K26waG9/NhoB3BSz6gNaONU6TQTuaavZdaoNRmznZHXASoOMO05omPyQ+1Nsihh9oGs7Kh1bGBIMQrtWs8Nn18cr1JQXNUOKQJ6UMvKsXq0C0GvPel5g3mTsOz7lCIIocFeM6H8n8vUumxHbbSsiGcZ6T1sutuLPfz3+mzqwgTj5tJ8SRwF/0ea/1KcIJLiIZsDLi0VV/Ao6aS0ZP0z5/hKOKdTVPfK9owQKjbabmKNilpW5Bc0+6X0DzC0sYL4u+79FnyBMKB6azwB/kigR7iiUax52O5QVwi/XOwJEWF0nrpP0ugnbvDufgSSOSiTHiowNA8cdpbJ7LtgiP8WboAP1RqDJ7yKAJi3c4WjL+lDRqaOEwZhuI1ZOKOzoGZdP9GbiKTzrn3rOHgeYUkSrPx9PMFTpvfNrVp5DnVdhuyBdn/ICRsnzIXvmqW4B4xyXo2bzk8VsU6sN7ds/wX/CqE5x3laUN1vzXP5alxU9KxqEKB+ofZCHQBidSKZm8NKMGu3zUsYt4T5GCjcYvj8FtUDddtuy1FFukNc/iJ2r+blXZzqFsdq9wQeKp/G0BLO99KHkdhN5CoeIjI3VYnXoAUG0Iq6e7SWxMu0LuD/lNm+1m3y53prjTxbfVgwDezewOAxq7BmmH0b5j3kpLsbHtd90LqlaNM5b4WA1RM5CerioTK8iiwXdMlMvU1I8rlNDuXuubD0ULtGhgKjfQZBtrpAJozSm66rXCsoEbMUrH4a9Ae4azAQF079bH8CGCiTkvowGFD+MKxHoJKPKIsgJy67FSW3r1N5IdpT3gk0g8CKAUUTvxqzOmOqqHm7vfWYegRQozu3QhOXuo9VGs7KyN7x4=
