job:
  name: "Sample LayoutLM Training Job"
  description: "A sample training job for LayoutLM on receipt data"
  priority: 5
  estimated_duration: 3600
  tags:
    - "sample"
    - "layoutlm"
    - "receipt"
  
  resources:
    instance_type: "p3.2xlarge"
    min_gpu_count: 1
    max_gpu_count: 1
    spot_instance: true
    max_runtime: 86400
  
  model:
    type: "layoutlm"
    version: "v2"
    pretrained_model_name: "microsoft/layoutlm-base-uncased"
    max_seq_length: 512
    doc_stride: 128
  
  training:
    epochs: 10
    batch_size: 4
    gradient_accumulation_steps: 2
    learning_rate: 3.0e-5
    weight_decay: 0.01
    warmup_ratio: 0.1
    early_stopping:
      enabled: true
      patience: 3
      metric: "val_f1"
      mode: "max"
    mixed_precision: true
  
  dataset:
    train_data:
      - type: "dynamodb"
        table: "ReceiptTrainingData"
        query_params:
          split: "train"
      - type: "sroie"
        path: "s3://receipt-data/sroie/train"
    validation_data:
      - type: "dynamodb"
        table: "ReceiptTrainingData"
        query_params:
          split: "validation"
    test_data:
      - type: "dynamodb"
        table: "ReceiptTrainingData"
        query_params:
          split: "test"
    data_augmentation:
      enabled: true
      methods:
        - "rotation"
        - "scaling"
        - "perspective_transform"
      probabilities:
        rotation: 0.3
        scaling: 0.2
        perspective_transform: 0.1
  
  checkpoints:
    save_strategy: "epoch"
    save_total_limit: 3
    metrics_to_track:
      - "loss"
      - "f1"
      - "precision"
      - "recall"
  
  output:
    base_s3_path: "s3://receipt-models/layoutlm-training"
    save_model: true
    save_optimizer_state: false
  
  wandb:
    enabled: true
    project: "receipt-recognition"
    entity: "receipt-team"
    tags:
      - "layoutlm"
      - "training"
  
  notifications:
    on_completion:
      - "email"
    on_failure:
      - "email"
      - "slack"
    recipients:
      email:
        - "team@example.com"
      slack:
        - "#model-training"
  
  dependencies: [] 