# Example job definition with dependencies
name: Fine-tuning Job with Dependencies
description: A LayoutLM fine-tuning job that depends on pre-processing and data preparation jobs

# Job metadata
priority: high
estimated_duration: 3600  # seconds
tags:
  environment: production
  model_type: layoutlm
  dataset: receipts

# Dependencies configuration
dependencies:
  - job_id: 2a6b74e1-3c9d-4f8a-9b7c-5d0e3f1a8e2d
    type: SUCCESS
    description: Data Preprocessing Job

  - job_id: f5c83a2e-6d7b-4e0f-a1c9-0d8e7f6a5b4c
    type: ARTIFACT
    condition: s3://bucket/preprocessed/data.zip
    description: Dataset Preparation Job

# Job configuration for LayoutLM training
config:
  # Model configuration
  model:
    name: microsoft/layoutlm-base-uncased
    max_seq_length: 512
    
  # Training configuration
  training:
    batch_size: 8
    learning_rate: 2e-5
    num_epochs: 5
    weight_decay: 0.01
    warmup_steps: 500
    gradient_accumulation_steps: 4
    use_fp16: true
    
  # Data configuration
  data:
    train_files:
      - s3://bucket/preprocessed/train.jsonl
    validation_files:
      - s3://bucket/preprocessed/val.jsonl
    test_files:
      - s3://bucket/preprocessed/test.jsonl
    
  # Optimization configuration
  optimization:
    early_stopping:
      patience: 3
      metric: eval_f1
      mode: max
    
  # Checkpoint configuration
  checkpoints:
    save_total_limit: 3
    save_steps: 1000
    
  # Output configuration
  output:
    model_dir: s3://bucket/models/fine-tuned/
    tensorboard_dir: s3://bucket/logs/tensorboard/
    
  # Resource configuration
  resources:
    gpu_count: 1
    gpu_type: V100
    memory: 16G
    
  # Notifications
  notifications:
    email:
      - data_scientist@example.com
    slack:
      channel: model-training-alerts 