job:
  # Basic job metadata
  name: "layoutlm-receipt-training-v1"
  description: "Training LayoutLM model on receipt dataset with basic hyperparameters"
  priority: 5  # 1-10 scale
  estimated_duration: 7200  # in seconds (2 hours)
  tags: ["receipt", "layoutlm", "production"]
  
  # Resource requirements
  resources:
    instance_type: "p3.2xlarge"  # AWS GPU instance
    min_gpu_count: 1
    max_gpu_count: 1
    spot_instance: true
    max_runtime: 86400  # max runtime in seconds (24 hours)
    
  # Model configuration
  model:
    type: "layoutlm"
    version: "v2"
    pretrained_model_name: "microsoft/layoutlm-base-uncased"
    max_seq_length: 512
    doc_stride: 128
    
  # Training configuration
  training:
    epochs: 10
    batch_size: 8
    gradient_accumulation_steps: 4
    learning_rate: 5e-5
    weight_decay: 0.01
    warmup_ratio: 0.1
    early_stopping:
      enabled: true
      patience: 3
      metric: "val_f1"
      mode: "max"
    mixed_precision: true
    
  # Dataset configuration
  dataset:
    train_data:
      - type: "dynamodb"
        table: "receipts-dev"
        query_params:
          tags: ["train", "validated"]
      - type: "sroie"
        path: "s3://receipt-data/sroie/train"
    validation_data:
      - type: "dynamodb"
        table: "receipts-dev"
        query_params:
          tags: ["validation", "validated"]
    data_augmentation:
      enabled: true
      methods: ["rotation", "scaling", "noise"]
      
  # Checkpointing configuration
  checkpoints:
    save_strategy: "epoch"
    save_total_limit: 3
    metrics_to_track: ["loss", "f1", "precision", "recall"]
    
  # Output configuration
  output:
    base_s3_path: "s3://receipt-models/training-runs/"
    save_model: true
    save_optimizer_state: true
    
  # Weights & Biases integration
  wandb:
    enabled: true
    project: "receipt-ocr"
    entity: "your-team"
    tags: ["layoutlm", "production-training"]
    
  # Notification configuration
  notifications:
    on_completion: ["email", "slack"]
    on_failure: ["email", "slack"]
    recipients:
      email: ["your-email@example.com"]
      slack: ["#ml-training-updates"] 