from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from receipt_logo.receipt_fixture import ReceiptHeaderMatch, inspect_receipt_fixture
from receipt_logo.vectorize import (
    VectorizeOptions,
    VectorizeResult,
    render_svg,
    vectorize_logo,
    write_vector_asset,
    xml_escape,
)

DEFAULT_SPROUTS_SOURCE = Path.home() / "Downloads" / "Sprouts_Farmers_Market_Logo.png"
DEFAULT_PORTFOLIO_FIXTURE = None


@dataclass(frozen=True)
class ProofArtifacts:
    output_dir: str
    source_path: str
    svg_path: str
    manifest_path: str
    receipt_header_svg_path: str
    html_path: str
    receipt_fixture: dict | None
    vector_summary: dict


def build_sprouts_proof(
    source_path: str | Path = DEFAULT_SPROUTS_SOURCE,
    output_dir: str | Path = "proofs/sprouts",
    receipt_fixture_path: str | Path | None = DEFAULT_PORTFOLIO_FIXTURE,
) -> ProofArtifacts:
    """Create the Sprouts source-of-truth proof assets."""

    out = Path(output_dir).expanduser().resolve()
    out.mkdir(parents=True, exist_ok=True)
    source = Path(source_path).expanduser().resolve()

    result = vectorize_logo(
        source,
        VectorizeOptions(
            max_colors=2,
            simplify_tolerance=1.35,
            min_contour_area=8.0,
            title="Sprouts Farmers Market logo",
        ),
    )
    svg_path, manifest_path = write_vector_asset(result, out, "sprouts_farmers_market")

    header_match = None
    if receipt_fixture_path:
        fixture = Path(receipt_fixture_path).expanduser()
        if fixture.exists():
            header_match = inspect_receipt_fixture(fixture)

    receipt_header_svg_path = out / "sprouts_receipt_header.svg"
    receipt_header_svg_path.write_text(
        render_receipt_header_svg(result, header_match),
        encoding="utf-8",
    )

    manifest = result.manifest(str(svg_path))
    manifest.update(
        {
            "merchant_slug": "sprouts_farmers_market",
            "receipt_fixture": header_match.to_dict() if header_match else None,
            "receipt_header_svg_path": str(receipt_header_svg_path),
            "notes": [
                "Generated by the receipt_logo package.",
                "Receipt fixtures are read-only and used only for placement proof.",
            ],
        }
    )
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    html_path = out / "index.html"
    html_path.write_text(
        render_proof_html(source, svg_path, receipt_header_svg_path, manifest),
        encoding="utf-8",
    )

    vector_summary = {
        "width": result.width,
        "height": result.height,
        "visible_pixel_count": result.visible_pixel_count,
        "palette": list(result.palette),
        "layer_count": len(result.layers),
        "path_count": sum(layer.path_count for layer in result.layers),
        "point_count": sum(layer.point_count for layer in result.layers),
    }

    return ProofArtifacts(
        output_dir=str(out),
        source_path=str(source),
        svg_path=str(svg_path),
        manifest_path=str(manifest_path),
        receipt_header_svg_path=str(receipt_header_svg_path),
        html_path=str(html_path),
        receipt_fixture=header_match.to_dict() if header_match else None,
        vector_summary=vector_summary,
    )


def render_receipt_header_svg(
    result: VectorizeResult,
    header_match: ReceiptHeaderMatch | None,
) -> str:
    logo_svg = render_svg(
        result.width,
        result.height,
        "Sprouts Farmers Market receipt-scale path logo",
        result.layers,
        fill_override="#111111",
    )
    path_lines = [
        line for line in logo_svg.splitlines() if line.strip().startswith("<path ")
    ]
    header_note = ""
    if header_match:
        header_note = (
            f"Read-only fixture header bounds: {header_match.bounds}, "
            f"{header_match.width}x{header_match.height}"
        )
    else:
        header_note = (
            "No receipt fixture header found; rendered with default "
            "receipt-scale placement."
        )

    scale_width = 280
    scale = scale_width / result.width
    y = 28
    x = 20

    return "\n".join(
        [
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 160" role="img">',
            "  <title>Sprouts path logo receipt-scale proof</title>",
            '  <rect x="0" y="0" width="320" height="160" fill="#f7f4ed"/>',
            '  <rect x="12" y="10" width="296" height="140" rx="3" fill="#fffef8" stroke="#ddd6c8"/>',
            f'  <g transform="translate({x} {y}) scale({scale:.6f})">',
            *[f"    {line.strip()}" for line in path_lines],
            "  </g>",
            '  <line x1="48" y1="101" x2="272" y2="101" stroke="#111" stroke-width="1"/>',
            '  <text x="160" y="119" text-anchor="middle" font-family="Menlo, monospace" font-size="8" fill="#333">PATH LOGO · RECEIPT SCALE</text>',
            f"  <desc>{xml_escape(header_note)}</desc>",
            "</svg>",
            "",
        ]
    )


def render_proof_html(
    source_path: Path,
    svg_path: Path,
    receipt_header_svg_path: Path,
    manifest: dict,
) -> str:
    summary = {
        "palette": manifest["palette"],
        "layer_count": len(manifest["layers"]),
        "path_count": sum(layer["path_count"] for layer in manifest["layers"]),
        "point_count": sum(layer["point_count"] for layer in manifest["layers"]),
        "visible_pixel_count": manifest["visible_pixel_count"],
        "receipt_fixture": manifest.get("receipt_fixture"),
    }
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Sprouts Logo Path Proof</title>
  <style>
    body {{
      margin: 0;
      font: 14px/1.45 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: #f6f3ee;
      color: #1f261f;
    }}
    main {{
      max-width: 1180px;
      margin: 0 auto;
      padding: 28px;
    }}
    h1 {{
      font-size: 24px;
      margin: 0 0 18px;
      letter-spacing: 0;
    }}
    .grid {{
      display: grid;
      grid-template-columns: repeat(3, minmax(0, 1fr));
      gap: 18px;
      align-items: start;
    }}
    figure {{
      margin: 0;
      padding: 14px;
      background: #fffef8;
      border: 1px solid #ded8ca;
      border-radius: 6px;
    }}
    img {{
      display: block;
      width: 100%;
      height: auto;
      object-fit: contain;
    }}
    figcaption {{
      margin-top: 10px;
      font-size: 12px;
      color: #4f594f;
    }}
    pre {{
      margin-top: 18px;
      padding: 14px;
      overflow: auto;
      background: #20251f;
      color: #e6efdf;
      border-radius: 6px;
    }}
    @media (max-width: 800px) {{
      .grid {{ grid-template-columns: 1fr; }}
    }}
  </style>
</head>
<body>
  <main>
    <h1>Sprouts Logo Path Proof</h1>
    <div class="grid">
      <figure>
        <img src="{source_path.as_uri()}" alt="Source Sprouts PNG">
        <figcaption>Downloaded PNG source of truth.</figcaption>
      </figure>
      <figure>
        <img src="{svg_path.name}" alt="Traced Sprouts SVG path">
        <figcaption>Generated SVG path asset.</figcaption>
      </figure>
      <figure>
        <img src="{receipt_header_svg_path.name}" alt="Receipt-scale Sprouts path logo">
        <figcaption>Monochrome receipt-scale path placement.</figcaption>
      </figure>
    </div>
    <pre>{xml_escape(json.dumps(summary, indent=2))}</pre>
  </main>
</body>
</html>
"""
