# Example training job configuration
# Usage: receipt-trainer submit-job --config training_job.yaml --queue-url <SQS_QUEUE_URL>

# Basic job information
job_name: Train LayoutLM for Receipt OCR
description: Fine-tune LayoutLM model for receipt field extraction
tags:
  project: receipt-ocr
  environment: production
  owner: data-science-team

# Model specification
model: microsoft/layoutlm-base-uncased

# Training configuration
training_config:
  # Training parameters
  num_epochs: 5
  batch_size: 8
  learning_rate: 5.0e-5
  weight_decay: 0.01

  # Logging parameters
  logging_steps: 100
  eval_steps: 500
  save_steps: 1000

  # Output directory (will be overridden on spot instances to use EFS)
  output_dir: ./output

  # Advanced parameters
  gradient_accumulation_steps: 2
  fp16: true
  early_stopping_patience: 3

# Data configuration
data_config:
  # Dataset parameters
  dataset_name: internal-receipts
  train_split: train
  eval_split: validation

  # Data filtering
  min_confidence: 0.7
  max_samples: 10000

  # Data processing
  use_sliding_window: true
  window_size: 512
  stride: 128

  # Data augmentation
  augmentation_probability: 0.2
  rotation_range: 5
  translate_percent: 0.02
