import Foundation
import Testing

@testable import ReceiptOCRCore

/// Golden parity gate for the Swift port of the Python band-block
/// line-item decoder.
///
/// - `Fixtures/line_items_golden_ocr.json` is a byte copy of
///   `receipt_upload/tests/fixtures/line_items_golden_ocr.json` (35
///   receipts: words + items_line_ids).
/// - `Fixtures/line_items_parity_expected.json` and
///   `Fixtures/line_items_guard_parity_expected.json` are GENERATED by
///   `receipt_ocr_swift/Scripts/generate_line_items_parity.py` from the
///   live Python decoder.
///
/// ANTI-DRIFT: none of these files may be hand-edited. The Python matrix
/// test `receipt_upload/tests/test_swift_line_item_parity_fixture.py`
/// re-runs that generator on every CI run and fails when the committed
/// bytes differ, so the snapshot cannot silently freeze against a moving
/// Python again (it did between #1313 and #1329: "33/33 parity" was
/// agreement with a Python that no longer existed).
///
/// The Swift decoder must reproduce the Python output exactly: same item
/// count, same order, same name strings, prices equal to 2 decimals,
/// nil-safe quantity/unit_price to 2 decimals, same is_discount, same
/// name_quality, same line_ids — unfiltered AND with the #1320 summary
/// figure filter, plus the #1324 reconciliation grade, the #1321 printed
/// total fallback and the #1329 boundary proposal.
///
/// Uses swift-testing (not XCTest) so the suite also runs on machines with
/// only CommandLineTools, which ship Testing.framework but no XCTest.
@Suite struct LineItemParityTests {

    // MARK: - Fixture shapes

    struct OCRFixture: Decodable {
        let receipts: [OCRReceipt]
    }

    struct OCRReceipt: Decodable {
        let imageId: String
        let receiptId: Int
        let merchant: String?
        let itemsLineIds: [Int]
        let words: [ZoneWord]

        enum CodingKeys: String, CodingKey {
            case imageId = "image_id"
            case receiptId = "receipt_id"
            case merchant
            case itemsLineIds = "items_line_ids"
            case words
        }
    }

    struct ExpectedSummary: Decodable {
        let subtotal: Double?
        let tax: Double?
        let grandTotal: Double?

        enum CodingKeys: String, CodingKey {
            case subtotal
            case tax
            case grandTotal = "grand_total"
        }

        var asSummary: LineItemSummary {
            LineItemSummary(
                subtotal: subtotal, tax: tax, grandTotal: grandTotal
            )
        }
    }

    struct ExpectedReconcile: Decodable {
        let status: String
        let itemSum: Double?
        let baseline: Double?
        let baselineSource: String?
        let baselineFiguresAgreeing: Int?

        enum CodingKeys: String, CodingKey {
            case status
            case itemSum = "item_sum"
            case baseline
            case baselineSource = "baseline_source"
            case baselineFiguresAgreeing = "baseline_figures_agreeing"
        }
    }

    struct ExpectedPrinted: Decodable {
        let grandTotal: Double?
        let subtotal: Double?

        enum CodingKeys: String, CodingKey {
            case grandTotal = "grand_total"
            case subtotal
        }
    }

    struct ExpectedRow: Decodable {
        let rowId: Int
        let lineIds: [Int]
        let yMin: Double?

        enum CodingKeys: String, CodingKey {
            case rowId = "row_id"
            case lineIds = "line_ids"
            case yMin = "y_min"
        }
    }

    struct ExpectedZoneEval: Decodable {
        let status: String
        let itemsSum: Double?
        let baseline: Double?
        let delta: Double?
        let nItems: Int

        enum CodingKeys: String, CodingKey {
            case status
            case itemsSum = "items_sum"
            case baseline
            case delta
            case nItems = "n_items"
        }
    }

    struct ExpectedProposal: Decodable {
        let lineIds: [Int]
        let addedLineIds: [Int]
        let addedRowIds: [Int]
        let before: ExpectedZoneEval
        let after: ExpectedZoneEval

        enum CodingKeys: String, CodingKey {
            case lineIds = "line_ids"
            case addedLineIds = "added_line_ids"
            case addedRowIds = "added_row_ids"
            case before
            case after
        }
    }

    struct ExpectedBoundary: Decodable {
        let currentLineIds: [Int]
        let rows: [ExpectedRow]
        let summary: ExpectedSummary?
        let proposal: ExpectedProposal?

        enum CodingKeys: String, CodingKey {
            case currentLineIds = "current_line_ids"
            case rows
            case summary
            case proposal
        }
    }

    struct ExpectedReceipt: Decodable {
        let imageId: String
        let receiptId: Int
        let merchant: String?
        let items: [ExpectedItem]
        let summary: ExpectedSummary?
        let itemsWithSummary: [ExpectedItem]
        let reconcile: ExpectedReconcile
        let printed: ExpectedPrinted
        let boundary: ExpectedBoundary

        enum CodingKeys: String, CodingKey {
            case imageId = "image_id"
            case receiptId = "receipt_id"
            case merchant
            case items
            case summary
            case itemsWithSummary = "items_with_summary"
            case reconcile
            case printed
            case boundary
        }
    }

    struct ExpectedItem: Decodable {
        let name: String
        let price: Double
        let quantity: Double?
        let unitPrice: Double?
        let isDiscount: Bool
        let nameQuality: String?
        let lineIds: [Int]

        enum CodingKeys: String, CodingKey {
            case name
            case price
            case quantity
            case unitPrice = "unit_price"
            case isDiscount = "is_discount"
            case nameQuality = "name_quality"
            case lineIds = "line_ids"
        }
    }

    struct GuardCase: Decodable {
        let name: String
        let words: [ZoneWord]
        let itemsLineIds: [Int]
        let items: [ExpectedItem]

        enum CodingKeys: String, CodingKey {
            case name = "case"
            case words
            case itemsLineIds = "items_line_ids"
            case items
        }
    }

    // MARK: - Helpers

    static var fixturesURL: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures")
    }

    private func load<T: Decodable>(_ name: String, as type: T.Type) throws
        -> T
    {
        let url = Self.fixturesURL.appendingPathComponent(name)
        return try JSONDecoder().decode(T.self, from: Data(contentsOf: url))
    }

    /// Nil-safe equality to 2 decimals.
    private func eq2(_ a: Double?, _ b: Double?) -> Bool {
        switch (a, b) {
        case (nil, nil):
            return true
        case let (x?, y?):
            return abs(x - y) <= 0.005
        default:
            return false
        }
    }

    private func fmt(_ v: Double?) -> String {
        v.map { String($0) } ?? "nil"
    }

    private func fmt(_ v: Int?) -> String {
        v.map { String($0) } ?? "nil"
    }

    /// Item-by-item comparison; returns one message per disagreement.
    private func diffItems(
        _ got: [DecodedLineItem], _ expected: [ExpectedItem], label: String
    ) -> [String] {
        if got.count != expected.count {
            return [
                "\(label): item count \(got.count) != \(expected.count); "
                    + "got names: \(got.map(\.name))"
            ]
        }
        var failures: [String] = []
        for (idx, (g, e)) in zip(got, expected).enumerated() {
            var diffs: [String] = []
            if g.name != e.name {
                diffs.append("name \"\(g.name)\" != \"\(e.name)\"")
            }
            if !eq2(g.price, e.price) {
                diffs.append("price \(g.price) != \(e.price)")
            }
            if !eq2(g.quantity, e.quantity) {
                diffs.append(
                    "quantity \(fmt(g.quantity)) != \(fmt(e.quantity))"
                )
            }
            if !eq2(g.unitPrice, e.unitPrice) {
                diffs.append(
                    "unit_price \(fmt(g.unitPrice)) != \(fmt(e.unitPrice))"
                )
            }
            if g.isDiscount != e.isDiscount {
                diffs.append("is_discount \(g.isDiscount) != \(e.isDiscount)")
            }
            if g.nameQuality != e.nameQuality {
                diffs.append(
                    "name_quality \(g.nameQuality ?? "nil") "
                        + "!= \(e.nameQuality ?? "nil")"
                )
            }
            if Set(g.lineIds) != Set(e.lineIds) {
                diffs.append("line_ids \(g.lineIds) != \(e.lineIds)")
            }
            if !diffs.isEmpty {
                failures.append(
                    "\(label): item[\(idx)]: " + diffs.joined(separator: "; ")
                )
            }
        }
        return failures
    }

    // MARK: - The gate

    @Test func goldenParityAcrossTheWholeGoldenSet() throws {
        let ocr = try load("line_items_golden_ocr.json", as: OCRFixture.self)
        let expected = try load(
            "line_items_parity_expected.json", as: [ExpectedReceipt].self
        )
        // The count is NOT hardcoded: the golden set grows (33 -> 35 at the
        // 2026-08 batch) and a pinned number is one more thing that goes
        // stale. The generator's --check step owns the "is this the whole
        // canonical set" question.
        #expect(ocr.receipts.count == expected.count)
        #expect(ocr.receipts.count >= 35)

        var passed = 0
        var failures: [String] = []

        for (receipt, exp) in zip(ocr.receipts, expected) {
            #expect(receipt.imageId == exp.imageId)
            #expect(receipt.receiptId == exp.receiptId)
            let tag =
                "\(receipt.merchant ?? "?") "
                + "\(receipt.imageId)#\(receipt.receiptId)"
            let zone = Set(receipt.itemsLineIds)
            var receiptFailures: [String] = []

            // 1. Unfiltered decode (extract_items with no summary).
            receiptFailures += diffItems(
                extractLineItems(words: receipt.words, zoneLineIds: zone),
                exp.items,
                label: "unfiltered"
            )

            // 2. #1320 non-product band filter (extract_items with a summary).
            let summary = exp.summary?.asSummary
            let filtered = extractLineItems(
                words: receipt.words, zoneLineIds: zone, summary: summary
            )
            receiptFailures += diffItems(
                filtered, exp.itemsWithSummary, label: "filtered"
            )

            // 3. #1324 three-figure reconciliation baseline + grade.
            let recon = reconcileLineItemsDetailed(
                items: filtered.filter { !$0.isDiscount }, summary: summary
            )
            if recon.status != exp.reconcile.status {
                receiptFailures.append(
                    "reconcile status \(recon.status) "
                        + "!= \(exp.reconcile.status)"
                )
            }
            if !eq2(recon.itemSum, exp.reconcile.itemSum) {
                receiptFailures.append(
                    "reconcile item_sum \(fmt(recon.itemSum)) "
                        + "!= \(fmt(exp.reconcile.itemSum))"
                )
            }
            if !eq2(recon.baseline, exp.reconcile.baseline) {
                receiptFailures.append(
                    "reconcile baseline \(fmt(recon.baseline)) "
                        + "!= \(fmt(exp.reconcile.baseline))"
                )
            }
            if recon.baselineSource != exp.reconcile.baselineSource {
                receiptFailures.append(
                    "baseline_source \(recon.baselineSource ?? "nil") "
                        + "!= \(exp.reconcile.baselineSource ?? "nil")"
                )
            }
            if recon.baselineFiguresAgreeing
                != exp.reconcile.baselineFiguresAgreeing
            {
                receiptFailures.append(
                    "baseline_figures_agreeing "
                        + "\(fmt(recon.baselineFiguresAgreeing)) "
                        + "!= \(fmt(exp.reconcile.baselineFiguresAgreeing))"
                )
            }

            // 4. #1321 label-free printed total fallback.
            let printedWords = receipt.words.map {
                PrintedTotalWord(
                    lineId: $0.lineId, wordId: $0.wordId, text: $0.text,
                    y: $0.yMid - $0.h / 2, height: $0.h
                )
            }
            let gotGrand = PrintedTotals.grandTotal(words: printedWords)
            let gotSubtotal = PrintedTotals.subtotal(words: printedWords)
            if !eq2(gotGrand, exp.printed.grandTotal) {
                receiptFailures.append(
                    "printed grand_total \(fmt(gotGrand)) "
                        + "!= \(fmt(exp.printed.grandTotal))"
                )
            }
            if !eq2(gotSubtotal, exp.printed.subtotal) {
                receiptFailures.append(
                    "printed subtotal \(fmt(gotSubtotal)) "
                        + "!= \(fmt(exp.printed.subtotal))"
                )
            }

            // 5. #1329 zone-gap boundary extension.
            receiptFailures += diffBoundary(receipt: receipt, exp: exp)

            if receiptFailures.isEmpty {
                passed += 1
            } else {
                failures.append(
                    "\(tag):\n  " + receiptFailures.joined(separator: "\n  ")
                )
            }
        }

        #expect(
            passed == expected.count,
            Comment(
                rawValue: "parity \(passed)/\(expected.count); failures:\n"
                    + failures.joined(separator: "\n")
            )
        )
    }

    private func diffBoundary(
        receipt: OCRReceipt, exp: ExpectedReceipt
    ) -> [String] {
        let boundary = exp.boundary
        let proposal = proposeItemsBoundaryExtension(
            words: receipt.words,
            summary: boundary.summary?.asSummary,
            currentLineIds: Set(boundary.currentLineIds),
            sections: [],
            rows: boundary.rows.map {
                BoundaryRow(
                    rowId: $0.rowId, lineIds: $0.lineIds, yMin: $0.yMin
                )
            }
        )
        guard let want = boundary.proposal else {
            guard let got = proposal else { return [] }
            return [
                "boundary: expected no proposal, got \(got.addedLineIds)"
            ]
        }
        guard let got = proposal else {
            return ["boundary: expected \(want.addedLineIds), got nil"]
        }
        var diffs: [String] = []
        if got.addedLineIds != want.addedLineIds {
            diffs.append(
                "boundary added_line_ids \(got.addedLineIds) "
                    + "!= \(want.addedLineIds)"
            )
        }
        if got.lineIds != want.lineIds {
            diffs.append(
                "boundary line_ids \(got.lineIds) != \(want.lineIds)"
            )
        }
        if got.addedRowIds != want.addedRowIds {
            diffs.append(
                "boundary added_row_ids \(got.addedRowIds) "
                    + "!= \(want.addedRowIds)"
            )
        }
        if got.after.status != want.after.status {
            diffs.append(
                "boundary after status \(got.after.status) "
                    + "!= \(want.after.status)"
            )
        }
        if !eq2(got.after.delta, want.after.delta) {
            diffs.append(
                "boundary after delta \(fmt(got.after.delta)) "
                    + "!= \(fmt(want.after.delta))"
            )
        }
        if !eq2(got.before.delta, want.before.delta) {
            diffs.append(
                "boundary before delta \(fmt(got.before.delta)) "
                    + "!= \(fmt(want.before.delta))"
            )
        }
        if got.after.nItems != want.after.nItems {
            diffs.append(
                "boundary after n_items \(got.after.nItems) "
                    + "!= \(want.after.nItems)"
            )
        }
        return diffs
    }

    /// The golden set does NOT exercise the #1320 non-product guards — the
    /// whole fixture decodes identically with the pre-#1320 regexes, which
    /// is exactly why the frozen Swift copies of SETTLEMENT_RE /
    /// SALE_PRICE_RE went unnoticed and NON_PRODUCT_NOTE_RE was never
    /// ported at all. These synthetic bands (a real product row plus one
    /// band that must not become an item) close that hole.
    @Test func nonProductGuardParity() throws {
        let cases = try load(
            "line_items_guard_parity_expected.json", as: [GuardCase].self
        )
        #expect(cases.count >= 19)

        var failures: [String] = []
        for testCase in cases {
            let got = extractLineItems(
                words: testCase.words,
                zoneLineIds: Set(testCase.itemsLineIds)
            )
            failures += diffItems(
                got, testCase.items, label: "guard[\(testCase.name)]"
            )
        }
        #expect(
            failures.isEmpty,
            Comment(rawValue: failures.joined(separator: "\n"))
        )
    }

    /// `is_proven` is a policy constant, not a decode: pinned directly.
    /// `near` NEVER counts, and a half-cent gap must not slip under the
    /// strict `< 0.005` line on float representation noise alone.
    @Test func isProvenPolicy() {
        #expect(
            isProven(
                reconStatus: "match", printedTotal: 21.07, bankAmount: 21.07
            )
        )
        #expect(
            !isProven(
                reconStatus: "near", printedTotal: 21.07, bankAmount: 21.07
            )
        )
        #expect(
            !isProven(
                reconStatus: "mismatch", printedTotal: 1.0, bankAmount: 1.0
            )
        )
        #expect(
            !isProven(reconStatus: nil, printedTotal: 1.0, bankAmount: 1.0)
        )
        #expect(
            !isProven(
                reconStatus: "match", printedTotal: nil, bankAmount: 1.0
            )
        )
        #expect(
            !isProven(
                reconStatus: "match", printedTotal: 1.0, bankAmount: nil
            )
        )
        // 21.075 - 21.07 == 0.004999... in binary floats; the mill rounding
        // must push it back onto the half-cent line so it FAILS.
        #expect(
            !isProven(
                reconStatus: "match", printedTotal: 21.075, bankAmount: 21.07
            )
        )
        #expect(
            isProven(
                reconStatus: "match", printedTotal: 21.074, bankAmount: 21.07
            )
        )
    }
}
