import Foundation
import Testing

@testable import ReceiptOCRCore

/// Golden parity gate for the Swift port of the Python band-block
/// line-item decoder.
///
/// - `Fixtures/line_items_golden_ocr.json` is a byte copy of
///   `receipt_upload/tests/fixtures/line_items_golden_ocr.json` (33
///   receipts: words + items_line_ids).
/// - `Fixtures/line_items_parity_expected.json` was generated by running
///   the PYTHON decoder (`receipt_upload.line_items.geometry.extract_items`)
///   over every fixture receipt and dumping name / price / quantity /
///   unit_price / is_discount / name_quality / line_ids per item.
///
/// The Swift decoder must reproduce the Python output exactly: same item
/// count, same order, same name strings, prices equal to 2 decimals,
/// nil-safe quantity/unit_price to 2 decimals, same is_discount, same
/// line_ids sets — on all 33 receipts.
///
/// Uses swift-testing (not XCTest) so the suite also runs on machines with
/// only CommandLineTools, which ship Testing.framework but no XCTest.
@Suite struct LineItemParityTests {

    struct OCRFixture: Decodable {
        let receipts: [OCRReceipt]
    }

    struct OCRReceipt: Decodable {
        let imageId: String
        let receiptId: Int
        let merchant: String?
        let itemsLineIds: [Int]
        let words: [ZoneWord]

        enum CodingKeys: String, CodingKey {
            case imageId = "image_id"
            case receiptId = "receipt_id"
            case merchant
            case itemsLineIds = "items_line_ids"
            case words
        }
    }

    struct ExpectedReceipt: Decodable {
        let imageId: String
        let receiptId: Int
        let items: [ExpectedItem]

        enum CodingKeys: String, CodingKey {
            case imageId = "image_id"
            case receiptId = "receipt_id"
            case items
        }
    }

    struct ExpectedItem: Decodable {
        let name: String
        let price: Double
        let quantity: Double?
        let unitPrice: Double?
        let isDiscount: Bool
        let nameQuality: String?
        let lineIds: [Int]

        enum CodingKeys: String, CodingKey {
            case name
            case price
            case quantity
            case unitPrice = "unit_price"
            case isDiscount = "is_discount"
            case nameQuality = "name_quality"
            case lineIds = "line_ids"
        }
    }

    static var fixturesURL: URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures")
    }

    private func load<T: Decodable>(_ name: String, as type: T.Type) throws
        -> T
    {
        let url = Self.fixturesURL.appendingPathComponent(name)
        return try JSONDecoder().decode(T.self, from: Data(contentsOf: url))
    }

    /// Nil-safe equality to 2 decimals.
    private func eq2(_ a: Double?, _ b: Double?) -> Bool {
        switch (a, b) {
        case (nil, nil):
            return true
        case let (x?, y?):
            return abs(x - y) <= 0.005
        default:
            return false
        }
    }

    private func fmt(_ v: Double?) -> String {
        v.map { String($0) } ?? "nil"
    }

    @Test func goldenParity33Receipts() throws {
        let ocr = try load(
            "line_items_golden_ocr.json", as: OCRFixture.self
        )
        let expected = try load(
            "line_items_parity_expected.json", as: [ExpectedReceipt].self
        )
        #expect(ocr.receipts.count == 33, "fixture must hold 33 receipts")
        #expect(expected.count == 33, "expectations must hold 33 receipts")

        var passed = 0
        var failures: [String] = []

        for (receipt, exp) in zip(ocr.receipts, expected) {
            #expect(receipt.imageId == exp.imageId)
            #expect(receipt.receiptId == exp.receiptId)
            let tag =
                "\(receipt.merchant ?? "?") "
                + "\(receipt.imageId)#\(receipt.receiptId)"

            let got = extractLineItems(
                words: receipt.words,
                zoneLineIds: Set(receipt.itemsLineIds)
            )

            var receiptFailures: [String] = []
            if got.count != exp.items.count {
                receiptFailures.append(
                    "item count \(got.count) != \(exp.items.count); "
                        + "got names: \(got.map(\.name))"
                )
            } else {
                for (idx, (g, e)) in zip(got, exp.items).enumerated() {
                    var diffs: [String] = []
                    if g.name != e.name {
                        diffs.append("name \"\(g.name)\" != \"\(e.name)\"")
                    }
                    if !eq2(g.price, e.price) {
                        diffs.append("price \(g.price) != \(e.price)")
                    }
                    if !eq2(g.quantity, e.quantity) {
                        diffs.append(
                            "quantity \(fmt(g.quantity)) != \(fmt(e.quantity))"
                        )
                    }
                    if !eq2(g.unitPrice, e.unitPrice) {
                        diffs.append(
                            "unit_price \(fmt(g.unitPrice)) "
                                + "!= \(fmt(e.unitPrice))"
                        )
                    }
                    if g.isDiscount != e.isDiscount {
                        diffs.append(
                            "is_discount \(g.isDiscount) != \(e.isDiscount)"
                        )
                    }
                    if Set(g.lineIds) != Set(e.lineIds) {
                        diffs.append(
                            "line_ids \(g.lineIds) != \(e.lineIds)"
                        )
                    }
                    if !diffs.isEmpty {
                        receiptFailures.append(
                            "item[\(idx)]: " + diffs.joined(separator: "; ")
                        )
                    }
                }
            }

            if receiptFailures.isEmpty {
                passed += 1
            } else {
                failures.append(
                    "\(tag):\n  "
                        + receiptFailures.joined(separator: "\n  ")
                )
            }
        }

        #expect(
            passed == 33,
            Comment(
                rawValue: "parity \(passed)/33; failures:\n"
                    + failures.joined(separator: "\n")
            )
        )
    }
}
