"""Real barcode / QR tile generation for the synthetic-receipt renderer.

The synthetic renderer used to *fake* its footer anchors: a QR drawn from
random 50/50 modules (no real finder timing / format info, not scannable) and a
1D "barcode" of random-width bars with a random human-readable digit caption.
The realism review flagged both ("fake/random bars", and "human-readable digits
under the barcode the real one lacks").

This module replaces those with *real* codes generated purely in Python so the
loop stays self-contained (NO Ghostscript / treepoem):

* ``render_qr_tile`` -> ``segno`` (a real, scannable QR symbol).
* ``render_barcode_tile`` -> ``python-barcode`` (real Code128 / UPC-A bar
  geometry, optionally with the human-readable interpretation line).

Both return paper-toned grayscale ``PIL.Image`` tiles. The caller pastes them
into a real blank band on the receipt and then runs the whole image through the
shared paper-texture degradation pass, so the codes age with the rest of the
print instead of looking pasted on top.
"""

from __future__ import annotations

import io

from PIL import Image

# Thermal-ink near-black and warm receipt-paper white. Kept in sync with the
# renderer's ``RenderConfig.background`` (250, 249, 245) so the tile quiet zone
# blends into the surrounding paper before the texture pass runs.
INK_HEX = "#141414"
PAPER_HEX = "#faf9f5"

_SUPPORTED_KINDS = {"code128", "upca"}


def render_qr_tile(data: str, size_px: int, seed: int = 0) -> Image.Image:
    """Render ``data`` as a real QR symbol, returned as a grayscale ``L`` tile.

    The symbol is generated by ``segno`` (so it carries valid finder patterns,
    timing rows and format info and actually scans), drawn at an integer module
    scale, then resampled with nearest-neighbour to ``size_px`` so the module
    grid stays crisp. ``seed`` is accepted for signature symmetry with
    ``render_barcode_tile``; QR content determinism comes from ``data`` itself.
    """
    import segno

    size_px = max(21, int(size_px))
    qr = segno.make(str(data), error="m")
    # Render large-and-square first (quiet zone = border), then resize down. A
    # generous scale keeps the down-sample from smearing module edges.
    buf = io.BytesIO()
    qr.save(buf, kind="png", scale=12, border=3, dark=INK_HEX, light=PAPER_HEX)
    buf.seek(0)
    tile = Image.open(buf).convert("L")
    if tile.size != (size_px, size_px):
        tile = tile.resize((size_px, size_px), Image.NEAREST)
    return tile


def _normalize_barcode_data(data: str, kind: str) -> str:
    digits = "".join(ch for ch in str(data) if ch.isdigit())
    if kind == "upca":
        # UPC-A wants 11 payload digits (python-barcode appends the 12th check
        # digit). Pad / trim deterministically from whatever we were handed.
        if len(digits) < 11:
            digits = (digits + "0" * 11)[:11]
        return digits[:11]
    # Code128 can carry the raw string; fall back to digits so it stays a
    # plausible numeric transaction barcode.
    return str(data) if data else (digits or "0")


def render_barcode_tile(
    data: str,
    kind: str,
    w_px: int,
    h_px: int,
    with_hri: bool = False,
) -> Image.Image:
    """Render a real 1D barcode as a grayscale ``L`` tile sized ``w_px`` x ``h_px``.

    ``kind`` is one of ``{"code128", "upca"}``. ``with_hri`` controls the
    human-readable interpretation line printed beneath the bars; it defaults to
    ``False`` because most receipt footer barcodes are printed *without* a digit
    caption, and the spurious caption was one of the realism tells.
    """
    import barcode
    from barcode.writer import ImageWriter

    kind = kind if kind in _SUPPORTED_KINDS else "code128"
    w_px = max(40, int(w_px))
    h_px = max(20, int(h_px))
    payload = _normalize_barcode_data(data, kind)

    writer = ImageWriter()
    # ``module_height`` is in mm; pick a value that gives the writer a tall-ish
    # raster which we then resample to the requested pixel box. The actual
    # aspect is governed by the resize below, so this only needs to be sane.
    options = {
        "write_text": bool(with_hri),
        "quiet_zone": 1.0,
        "module_height": 12.0,
        "module_width": 0.3,
        "background": PAPER_HEX,
        "foreground": INK_HEX,
        "dpi": 300,
    }
    if with_hri:
        options["font_size"] = 8
        options["text_distance"] = 3.0

    cls = barcode.get_barcode_class(kind)
    rendered = cls(payload, writer=writer).render(options)
    tile = rendered.convert("L")
    if tile.size != (w_px, h_px):
        # Bars are vertical: resample so widths stay as even as possible. NEAREST
        # keeps hard bar edges (scanner-friendly) without antialias gray fringe.
        tile = tile.resize((w_px, h_px), Image.NEAREST)
    return tile


# ---------------------------------------------------------------------------
# Merchant -> graphics profile
# ---------------------------------------------------------------------------

# Warehouse / big-box transaction footers print a long alphanumeric transaction
# barcode (Code128). Traditional grocers' transaction barcode reads as a
# UPC-A-style symbol. This is a "where sensible" heuristic, not ground truth.
_UPCA_MERCHANTS = ("vons", "sprouts", "smith", "gelson", "ralph", "albertson")


def graphics_profile_for_merchant(merchant: str | None) -> dict:
    """Return placement-agnostic graphics choices keyed off the merchant.

    Currently just selects the 1D barcode symbology and whether a QR anchor is
    expected. Kept tiny and deterministic so callers can extend it without
    reaching back into renderer internals.
    """
    name = (merchant or "").strip().lower()
    kind = "code128"
    if any(token in name for token in _UPCA_MERCHANTS):
        kind = "upca"
    return {
        "barcode_kind": kind,
        # Receipt footers carry the transaction barcode without a printed digit
        # caption; the QR (when present) is the scannable anchor.
        "barcode_with_hri": False,
        "qr": True,
    }
