#!/usr/bin/env python3
"""
Load edge cases from JSON file into DynamoDB.

This script reads edge cases generated by generate_edge_cases.py and loads
them into DynamoDB as LabelEdgeCase entities.

Usage:
    # Load edge cases from default file
    python scripts/load_edge_cases_to_dynamo.py

    # Load from specific file
    python scripts/load_edge_cases_to_dynamo.py --input edge_case_candidates.json

    # Dry run (don't actually write to DynamoDB)
    python scripts/load_edge_cases_to_dynamo.py --dry-run

    # Update existing edge cases (increment statistics)
    python scripts/load_edge_cases_to_dynamo.py --update-existing
"""

import argparse
import json
import os
import sys
from datetime import datetime
from typing import Dict, List

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from receipt_dynamo import DynamoClient
from receipt_dynamo.entities.label_edge_case import LabelEdgeCase

try:
    from receipt_agent.config.settings import get_settings
except ImportError:
    print("Error: receipt_agent package not found. Install dependencies first.")
    sys.exit(1)


def load_edge_cases_from_json(file_path: str) -> Dict:
    """Load edge cases from JSON file."""
    with open(file_path, "r") as f:
        data = json.load(f)
    return data


def create_edge_case_from_dict(
    label_type: str, edge_case_data: Dict, created_by: str = "label-harmonizer"
) -> LabelEdgeCase:
    """Create a LabelEdgeCase entity from dictionary data."""
    return LabelEdgeCase(
        label_type=label_type,
        word_text=edge_case_data.get("word_text", ""),
        normalized_word=edge_case_data.get("normalized_word", ""),
        merchant_name=edge_case_data.get("merchant_name"),
        match_type=edge_case_data.get("match_type", "exact"),
        pattern=edge_case_data.get("pattern"),
        reason=edge_case_data.get("reason", ""),
        times_identified=edge_case_data.get("count", 0),  # Use count as initial times_identified
        false_positives=0,
        created_at=datetime.now().isoformat(),
        updated_at=datetime.now().isoformat(),
        created_by=created_by,
    )


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Load edge cases from JSON into DynamoDB"
    )
    parser.add_argument(
        "--input",
        type=str,
        default="edge_case_candidates.json",
        help="Input JSON file path (default: edge_case_candidates.json)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Dry run mode - don't actually write to DynamoDB",
    )
    parser.add_argument(
        "--update-existing",
        action="store_true",
        help="Update existing edge cases instead of skipping them",
    )
    parser.add_argument(
        "--created-by",
        type=str,
        default="label-harmonizer",
        help="Who created these edge cases (default: label-harmonizer)",
    )

    args = parser.parse_args()

    # Check if input file exists
    if not os.path.exists(args.input):
        print(f"Error: Input file '{args.input}' not found.")
        sys.exit(1)

    # Initialize DynamoDB client
    try:
        settings = get_settings()
        dynamo = DynamoClient(table_name=settings.dynamo_table_name)
    except Exception as e:
        print(f"Error initializing DynamoDB client: {e}")
        sys.exit(1)

    # Load edge cases from JSON
    print(f"Loading edge cases from {args.input}...")
    try:
        data = load_edge_cases_from_json(args.input)
    except Exception as e:
        print(f"Error loading JSON file: {e}")
        sys.exit(1)

    exact_matches = data.get("exact_matches", {})
    patterns = data.get("patterns", {})

    print(f"Found edge cases for {len(exact_matches)} label types")
    print(f"Found {len(patterns)} pattern-based edge cases")

    # Process exact matches
    total_added = 0
    total_updated = 0
    total_skipped = 0
    total_errors = 0

    print("\nProcessing exact matches...")
    for label_type, edge_cases in exact_matches.items():
        print(f"  {label_type}: {len(edge_cases)} cases")

        for edge_case_data in edge_cases:
            try:
                edge_case = create_edge_case_from_dict(
                    label_type, edge_case_data, args.created_by
                )

                if args.dry_run:
                    print(f"    [DRY RUN] Would add: {edge_case.word_text} -> {label_type}")
                    total_added += 1
                    continue

                # Check if edge case already exists
                existing = dynamo.check_edge_case_match(
                    word_text=edge_case.word_text,
                    label_type=label_type,
                    merchant_name=edge_case.merchant_name,
                )

                if existing:
                    if args.update_existing:
                        # Update statistics
                        existing.times_identified = max(
                            existing.times_identified, edge_case.times_identified
                        )
                        existing.updated_at = datetime.now().isoformat()
                        dynamo.update_edge_case_statistics(
                            existing,
                            times_identified=existing.times_identified,
                        )
                        print(
                            f"    Updated: {edge_case.word_text} -> {label_type} "
                            f"(times_identified={existing.times_identified})"
                        )
                        total_updated += 1
                    else:
                        print(
                            f"    Skipped (exists): {edge_case.word_text} -> {label_type}"
                        )
                        total_skipped += 1
                else:
                    # Add new edge case
                    dynamo.add_edge_case(edge_case)
                    print(
                        f"    Added: {edge_case.word_text} -> {label_type} "
                        f"(count={edge_case.times_identified})"
                    )
                    total_added += 1

            except Exception as e:
                print(f"    Error processing {edge_case_data.get('word_text', 'unknown')}: {e}")
                total_errors += 1

    # Process pattern-based edge cases
    print("\nProcessing pattern-based edge cases...")
    for label_type, pattern_cases in patterns.items():
        print(f"  {label_type}: {len(pattern_cases)} patterns")

        for pattern_data in pattern_cases:
            try:
                edge_case = LabelEdgeCase(
                    label_type=label_type,
                    word_text=pattern_data.get("word_text", ""),
                    normalized_word="",  # Not used for regex patterns
                    merchant_name=pattern_data.get("merchant_name"),
                    match_type="regex",
                    pattern=pattern_data.get("pattern"),
                    reason=pattern_data.get("reason", ""),
                    times_identified=pattern_data.get("count", 0),
                    false_positives=0,
                    created_at=datetime.now().isoformat(),
                    updated_at=datetime.now().isoformat(),
                    created_by=args.created_by,
                )

                if args.dry_run:
                    print(
                        f"    [DRY RUN] Would add pattern: {pattern_data.get('pattern')} -> {label_type}"
                    )
                    total_added += 1
                    continue

                # For regex patterns, we need to check differently
                # For now, just try to add (will fail if duplicate key)
                try:
                    dynamo.add_edge_case(edge_case)
                    print(
                        f"    Added pattern: {pattern_data.get('pattern')} -> {label_type}"
                    )
                    total_added += 1
                except Exception as e:
                    if "ConditionalCheckFailedException" in str(e) or "already exists" in str(e).lower():
                        if args.update_existing:
                            # Try to find and update
                            # Note: This is simplified - in practice you'd query by pattern
                            print(
                                f"    Pattern already exists: {pattern_data.get('pattern')} -> {label_type}"
                            )
                            total_skipped += 1
                        else:
                            print(
                                f"    Skipped (exists): {pattern_data.get('pattern')} -> {label_type}"
                            )
                            total_skipped += 1
                    else:
                        raise

            except Exception as e:
                print(f"    Error processing pattern {pattern_data.get('pattern', 'unknown')}: {e}")
                total_errors += 1

    # Summary
    print("\n" + "=" * 60)
    print("Summary")
    print("=" * 60)
    if args.dry_run:
        print(f"[DRY RUN] Would add: {total_added} edge cases")
    else:
        print(f"Added: {total_added} edge cases")
        print(f"Updated: {total_updated} edge cases")
        print(f"Skipped: {total_skipped} edge cases")
        print(f"Errors: {total_errors} edge cases")
    print("=" * 60)


if __name__ == "__main__":
    main()

