"""
Infrastructure for Label Evaluator Visualization Cache API.

This component creates an API Lambda that serves cached visualization data.
The viz-cache data is generated by the Label Evaluator Step Function's merged
EMR job (when run_analytics=true).

Note: The Step Function, EventBridge rule, and export Lambdas have been removed
since the Label Evaluator Step Function now handles viz-cache generation directly.
"""

import json
import os
from typing import Optional

import pulumi
import pulumi_aws as aws
from pulumi import (
    AssetArchive,
    ComponentResource,
    FileArchive,
    Input,
    Output,
    ResourceOptions,
)

# Get stack configuration
stack = pulumi.get_stack()

# Reference the lambdas directory
LAMBDAS_DIR = os.path.join(os.path.dirname(__file__), "lambdas")


class LabelEvaluatorVizCache(ComponentResource):
    """API Lambda for serving label evaluator visualization data.

    The viz-cache data is generated by the Label Evaluator Step Function's
    merged EMR job and stored in S3. This component provides an API to serve
    that cached data.
    """

    def __init__(
        self,
        name: str,
        *,
        cache_bucket_name: Input[str],
        opts: Optional[ResourceOptions] = None,
    ):
        super().__init__(
            f"custom:label-evaluator-viz-cache:{name}",
            name,
            None,
            opts,
        )

        region = aws.get_region().name
        account_id = aws.get_caller_identity().account_id

        # Convert to Output for proper resolution
        cache_bucket_output = Output.from_input(cache_bucket_name)

        # Store cache bucket name for external access
        self.cache_bucket_name = cache_bucket_output

        # ============================================================
        # API Lambda Role
        # ============================================================
        self.api_lambda_role = aws.iam.Role(
            f"{name}-api-role",
            assume_role_policy=json.dumps(
                {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Principal": {"Service": "lambda.amazonaws.com"},
                            "Action": "sts:AssumeRole",
                        }
                    ],
                }
            ),
            tags={"environment": stack},
            opts=ResourceOptions(parent=self),
        )

        # API Lambda policy - read from cache bucket
        aws.iam.RolePolicy(
            f"{name}-api-policy",
            role=self.api_lambda_role.id,
            policy=cache_bucket_output.apply(
                lambda bucket: json.dumps(
                    {
                        "Version": "2012-10-17",
                        "Statement": [
                            {
                                "Effect": "Allow",
                                "Action": [
                                    "logs:CreateLogGroup",
                                    "logs:CreateLogStream",
                                    "logs:PutLogEvents",
                                ],
                                "Resource": f"arn:aws:logs:{region}:{account_id}:*",
                            },
                            {
                                "Effect": "Allow",
                                "Action": ["s3:GetObject", "s3:ListBucket"],
                                "Resource": [
                                    f"arn:aws:s3:::{bucket}",
                                    f"arn:aws:s3:::{bucket}/*",
                                ],
                            },
                        ],
                    }
                )
            ),
            opts=ResourceOptions(parent=self),
        )

        # ============================================================
        # API Lambda (GET endpoint)
        # ============================================================
        self.api_lambda = aws.lambda_.Function(
            f"{name}-api-lambda",
            runtime="python3.12",
            architectures=["arm64"],
            role=self.api_lambda_role.arn,
            code=AssetArchive({".": FileArchive(LAMBDAS_DIR)}),
            handler="index.handler",
            environment=aws.lambda_.FunctionEnvironmentArgs(
                variables={
                    "S3_CACHE_BUCKET": cache_bucket_output,
                }
            ),
            memory_size=256,
            timeout=30,
            tags={"environment": stack},
            opts=ResourceOptions(parent=self),
        )

        aws.cloudwatch.LogGroup(
            f"{name}-api-lambda-logs",
            name=self.api_lambda.name.apply(lambda n: f"/aws/lambda/{n}"),
            retention_in_days=30,
            opts=ResourceOptions(parent=self),
        )

        # ============================================================
        # Exports
        # ============================================================
        self.register_outputs(
            {
                "api_lambda_arn": self.api_lambda.arn,
                "api_lambda_name": self.api_lambda.name,
                "cache_bucket_name": self.cache_bucket_name,
            }
        )


def create_label_evaluator_viz_cache(
    cache_bucket_name: Input[str],
    opts: Optional[ResourceOptions] = None,
) -> LabelEvaluatorVizCache:
    """Factory function to create Label Evaluator Viz Cache API.

    Args:
        cache_bucket_name: Name of the S3 bucket containing viz-cache data
        opts: Pulumi resource options
    """
    return LabelEvaluatorVizCache(
        f"label-evaluator-viz-cache-{stack}",
        cache_bucket_name=cache_bucket_name,
        opts=opts,
    )
