from pathlib import Path
from typing import Iterable, List

from receipt_dynamo.data.dynamo_client import DynamoClient
from receipt_dynamo.entities import ReceiptLine, ReceiptWord

def generate_batch_id() -> str: ...
def download_serialized_file(*, s3_bucket: str, s3_key: str) -> Path: ...
def deserialize_receipt_lines(filepath: Path) -> List[ReceiptLine]: ...
def deserialize_receipt_words(filepath: Path) -> List[ReceiptWord]: ...
def query_receipt_lines(dynamo_client: DynamoClient, image_id: str, receipt_id: int) -> list[ReceiptLine]: ...
def query_receipt_words(dynamo_client: DynamoClient, image_id: str, receipt_id: int) -> list[ReceiptWord]: ...
def set_pending_and_update_lines(dynamo_client: DynamoClient, lines: Iterable[ReceiptLine]) -> None: ...
def set_pending_and_update_words(dynamo_client: DynamoClient, words: Iterable[ReceiptWord]) -> None: ...
def write_ndjson(filepath: Path, rows: Iterable[dict]) -> None: ...
