"""Utilities for submitting and polling word embedding batches."""

from .poll import (
    download_openai_batch_result,
    get_openai_batch_status,
    get_receipt_descriptions,
    list_pending_embedding_batches,
    mark_batch_complete,
    # Removed: upsert_embeddings_to_pinecone (use ChromaDB instead)
    write_embedding_results_to_dynamo,
)
from .submit import (
    _format_word_context_embedding_input,
    add_batch_summary,
    chunk_into_embedding_batches,
    create_batch_summary,
    deserialize_receipt_words,
    download_serialized_words,
    format_word_context_embedding,
    generate_batch_id,
    list_receipt_words_with_no_embeddings,
    query_receipt_words,
    serialize_receipt_words,
    submit_openai_batch,
    update_word_embedding_status,
    upload_serialized_words,
    upload_to_openai,
    write_ndjson,
)

__all__ = [
    "list_receipt_words_with_no_embeddings",
    "chunk_into_embedding_batches",
    "serialize_receipt_words",
    "upload_serialized_words",
    "format_word_context_embedding",
    "write_ndjson",
    "generate_batch_id",
    "upload_to_openai",
    "submit_openai_batch",
    "create_batch_summary",
    "add_batch_summary",
    "query_receipt_words",
    "update_word_embedding_status",
    "download_serialized_words",
    "deserialize_receipt_words",
    "_format_word_context_embedding_input",
    "list_pending_embedding_batches",
    "get_openai_batch_status",
    "download_openai_batch_result",
    # Removed: "upsert_embeddings_to_pinecone",
    "write_embedding_results_to_dynamo",
    "mark_batch_complete",
    "get_receipt_descriptions",
]
