name: Auto-format Code

on:
  workflow_run:
    workflows: ["Main CI/CD Pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  format:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install formatters
        run: pip install black isort

      - name: Format Python code
        run: |
          # Format all Python files
          echo "Running black..."
          black receipt_dynamo receipt_label infra scripts spec || true
          
          echo "Running isort..."
          isort receipt_dynamo receipt_label infra scripts spec || true
          
          # Check if there are any changes
          if [[ -n $(git diff --name-only) ]]; then
            echo "Files were reformatted:"
            git diff --name-only
            
            git config user.email "action@github.com"
            git config user.name "GitHub Action"
            git add -A
            git commit -m "style: auto-format Python code [skip ci]

            Auto-formatting after successful CI run.
            
            Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
            
            # Push with retry logic
            for i in {1..3}; do
              echo "Attempting push (attempt $i)..."
              if git push; then
                echo "Successfully pushed formatting changes"
                break
              else
                echo "Push failed, pulling latest changes and retrying..."
                git pull --rebase origin main
                if [ $i -eq 3 ]; then
                  echo "Failed to push after 3 attempts"
                  exit 0  # Don't fail the workflow
                fi
              fi
            done
          else
            echo "No formatting changes needed"
          fi