name: Claude Manual Review Trigger

on:
  issue_comment:
    types: [created]

jobs:
  trigger-review:
    name: Trigger Claude Review
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/claude review')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Check permissions
        uses: actions/github-script@v7
        with:
          script: |
            const commenter = context.payload.comment.user.login;
            const repo = context.repo;
            
            // Check if user has write access
            try {
              const { data: perm } = await github.rest.repos.getCollaboratorPermissionLevel({
                ...repo,
                username: commenter
              });
              
              if (!['admin', 'write'].includes(perm.permission)) {
                await github.rest.issues.createComment({
                  ...repo,
                  issue_number: context.issue.number,
                  body: `❌ @${commenter} You need write access to trigger Claude reviews.`
                });
                core.setFailed('User lacks write permissions');
                return;
              }
            } catch (error) {
              console.log('Permission check failed:', error);
              core.setFailed('Permission check failed');
              return;
            }

      - name: Add review label
        uses: actions/github-script@v7
        with:
          script: |
            // Add the label to trigger review
            await github.rest.issues.addLabels({
              ...context.repo,
              issue_number: context.issue.number,
              labels: ['claude-review-requested']
            });
            
            // Remove skip label if present
            try {
              await github.rest.issues.removeLabel({
                ...context.repo,
                issue_number: context.issue.number,
                name: 'skip-claude-review'
              });
            } catch (e) {
              // Label might not exist, that's fine
            }
            
            // Acknowledge the request
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: '🤖 Claude review requested! The review will start in a few moments.\n\nTo skip future automatic reviews on this PR, add the `skip-claude-review` label.'
            });