name: Claude Debug

on:
  issue_comment:
    types: [created]

jobs:
  debug:
    name: Debug Claude
    if: contains(github.event.comment.body, '@claude-debug')
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      issues: write
      
    steps:
      - name: Debug info
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Event name:', context.eventName);
            console.log('Comment body:', context.payload.comment.body);
            console.log('Issue number:', context.payload.issue.number);
            console.log('Comment author:', context.payload.comment.user.login);