name: Claude Test

on:
  issue_comment:
    types: [created]

jobs:
  test-claude:
    name: Test Claude
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      issues: write
      
    steps:
      - name: Test response
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '🤖 Test response: Claude workflow is running! The consolidated workflow will be fixed shortly.'
            });