name: Auto-format PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  format:
    name: Auto-format Python Code
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Format code
        run: |
          pip install black isort
          
          # Format all Python files
          black receipt_dynamo receipt_label infra scripts spec || true
          isort receipt_dynamo receipt_label infra scripts spec || true
          
          # Check if there are changes
          if [[ -n $(git diff --name-only) ]]; then
            git config user.email "action@github.com"
            git config user.name "GitHub Action"
            git add -A
            git commit -m "style: auto-format Python code

            Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
            git push
            
            # Comment on PR
            gh pr comment ${{ github.event.pull_request.number }} \
              --body "🎨 I've automatically formatted your Python code. Please pull the latest changes."
          else
            echo "No formatting changes needed"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}