name: Lightning Tests (Under 60s)
on:
  pull_request:
    paths:
      - '**.py'

# Cancel previous runs
concurrency:
  group: lightning-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  # Ultra-fast tests that run in under 60 seconds total
  lightning-tests:
    name: Lightning Tests
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Minimal clone
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Cache everything aggressively
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ${{ env.pythonLocation }}
            **/.pytest_cache
          key: lightning-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            lightning-${{ runner.os }}-
      
      - name: Install minimal test dependencies only
        run: |
          pip install --no-deps pytest pytest-xdist pytest-timeout
          pip install --no-deps moto boto3
      
      - name: Install packages in editable mode (no deps)
        run: |
          pip install -e receipt_dynamo --no-deps
          pip install -e receipt_label --no-deps
      
      - name: Run critical unit tests only
        run: |
          # Run only the fastest, most critical tests from each package
          pytest receipt_dynamo/tests/unit/test_batch_summary.py \
                 receipt_dynamo/tests/unit/test_label_metadata.py \
                 receipt_label/receipt_label/tests/test_models.py \
            -n auto \
            --timeout=20 \
            --maxfail=1 \
            -x \
            --tb=line \
            -q \
            --no-header || echo "Some tests failed - check full test run"
      
      - name: Status
        if: always()
        run: |
          echo "⚡ Lightning tests completed"
          echo "Check main test workflow for comprehensive results"